# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TinkoffChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for TinkoffChat
  pod 'Firebase/Firestore', '7.8.0'
  pod 'SwiftLint'


target 'TinkoffChatTests' do
  
  inherit! :search_paths
end

end
